using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SeeDither")]
[assembly: AssemblyDescription("Absolute GoTo coordinate-offset dithering for Seestar S30/S50 mounts.")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("SeeDither")]
[assembly: AssemblyCopyright("Copyright © 2026")]
[assembly: ComVisible(false)]
[assembly: Guid("c4d2e5a1-7b3f-4e9d-9f2a-6f1c8b9a3d11")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0.0")]

[assembly: AssemblyMetadata("Id", "c4d2e5a1-7b3f-4e9d-9f2a-6f1c8b9a3d11")]
[assembly: AssemblyMetadata("Name", "SeeDither")]
[assembly: AssemblyMetadata("Author", "Carl S.")]
[assembly: AssemblyMetadata("Homepage", "")]
[assembly: AssemblyMetadata("Repository", "")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("ChangelogURL", "")]
[assembly: AssemblyMetadata("FeaturedImageURL", "")]
[assembly: AssemblyMetadata("ScreenshotURL", "")]
[assembly: AssemblyMetadata("AltScreenshotURL", "")]
[assembly: AssemblyMetadata("LongDescription", "Performs random absolute-coordinate dithering after exposures, designed for Seestar mounts whose guide pulses are unreliable.")]
